### ISSUE TITLE
在主线程中不能使用在class 中声明成员，运行报错

### ISSUE THREAD

**Issue by ll-huihui** [xieerduos/electron-template#2]
示例：
//  src/main/background.js
class MyClass {
  name = '';
  constructor() {
    this.name = '123';
  }
}
const my1 = new MyClass();
console.log('output->my1', my1);

//运行报错
// yarn electron:build

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                   14:49:34

 error  in ./src/main/background.js

Module parse failed: Unexpected token (144:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class MyClass {
>   name = '';
|   constructor() {
|     this.name = '123';

 @ multi ./src/main/background.js

 ERROR  Build failed with errors.
error Command failed with exit code 1.

**Comment by xieerduos** [comment]
> 示例： // src/main/background.js class MyClass { name = ''; constructor() { this.name = '123'; } } const my1 = new MyClass(); console.log('output->my1', my1);
> 
> //运行报错 // yarn electron:build
> 
> ERROR Failed to compile with 1 errors 14:49:34
> 
> error in ./src/main/background.js
> 
> Module parse failed: Unexpected token (144:7) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders | | class MyClass {
> 
> > name = '';
> > |   constructor() {
> > |     this.name = '123';
> 
> @ multi ./src/main/background.js
> 
> ERROR Build failed with errors. error Command failed with exit code 1.

从提供的错误信息来看，Webpack 报告了在解析 ./src/main/background.js 文件时遇到了一个 "Unexpected token" 错误。具体来说，Webpack 没有理解 name = ''; 这种类字段（class field）的语法。这是一个较新的 JavaScript 特性，可能还未被当前的配置所支持。

经测试，在你的vue.config.js中添加下面的配置可以解决该问题
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: (config) => {
        // Set up Babel loader for JS files
        config.module
          .rule('babel')
          .test(/\.js$/)
          .use('babel-loader')
          .loader('babel-loader')
          .end();
      },
    },
  },
};

```
